[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_flags = --before=no_reset
lib_deps =
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    bblanchon/ArduinoJson
